export function buildPythonEntry(directoryPath: string, planId: string): string {
  const pathLiteral = JSON.stringify(directoryPath)
  const planIdLiteral = JSON.stringify(planId)

  return `# Generated by Longstep. Recreate this file from Longstep when the storage path changes.
from pathlib import Path
import sys

_LONGSTEP_DIR = Path(${pathLiteral})
_PLAN_ID = ${planIdLiteral}
_TOOL_PATH = _LONGSTEP_DIR / "longstep.pyz"
_PLAN_PATH = _LONGSTEP_DIR / f"{_PLAN_ID}.json"

if not _TOOL_PATH.is_file() or not _PLAN_PATH.is_file():
    raise FileNotFoundError("Longstepのツールまたは計画JSONが見つかりません。Longstepで絶対パスを再設定してください。")

sys.path.insert(0, str(_TOOL_PATH))
from longstep_tool import add_goal as _add_goal
from longstep_tool import delete_goal as _delete_goal
from longstep_tool import get_goal as _get_goal
from longstep_tool import get_plan_summary as _get_plan_summary
from longstep_tool import list_goals as _list_goals
from longstep_tool import update_goal as _update_goal
from longstep_tool import update_plan as _update_plan


def get_plan_summary():
    """計画ID・計画名・最終目標・revisionを辞書で返す。"""
    return _get_plan_summary(_PLAN_PATH)


def list_goals():
    """目標ID・名前・粒度・状態・前提関係の一覧を返す。"""
    return _list_goals(_PLAN_PATH)


def get_goal(goal_id):
    """get_goal(goal_id) -> 指定目標の全項目と関連目標を持つ辞書。"""
    return _get_goal(_PLAN_PATH, goal_id)


def update_plan(**changes):
    """update_plan(name=, statement=, deadline=, success_criteria=) -> 更新結果。指定項目だけ更新する。"""
    return _update_plan(_PLAN_PATH, **changes)


def add_goal(name, **fields):
    """add_goal(name, target_date=, description=, next_action=, goal_level=, depends_on=, recurrence_enabled=, recurrence_cadence=, completed_count=) -> 更新結果。"""
    return _add_goal(_PLAN_PATH, name, **fields)


def update_goal(goal_id, **changes):
    """update_goal(goal_id, name=, status=, target_date=, description=, next_action=, goal_level=, depends_on=, recurrence_enabled=, recurrence_cadence=, completed_count=) -> 更新結果。"""
    return _update_goal(_PLAN_PATH, goal_id, **changes)


def delete_goal(goal_id):
    """delete_goal(goal_id) -> revisionと削除対象を持つ更新結果。"""
    return _delete_goal(_PLAN_PATH, goal_id)
`
}
