export const LONGSTEP_DIRECTORY_NAME = 'Longstep'
export const LONGSTEP_DIRECTORY_LABEL = '書類フォルダ内のLongstep'

/** Longstepが作った、その計画専用の入口かどうか。別計画へ差し替わった入口を消さないために使う。 */
export function isPythonEntryForPlan(text: string, planId: string): boolean {
  return text.startsWith('# Generated by Longstep') && text.includes(`_PLAN_ID = ${JSON.stringify(planId)}\n`)
}

export function buildPythonEntry(planId: string): string {
  const planIdLiteral = JSON.stringify(planId)

  return `# Generated by Longstep. Recreate this file from Longstep when the plan changes.
"""この計画専用のLongstep入口。長期計画の取得・部分更新をおこなう。

計画データの場所: ~/Documents/${LONGSTEP_DIRECTORY_NAME}/${planId}.json

【AIエージェントへ：実行前に必ず確認すること】
VM・サンドボックス・コンテナ・リモート環境で動作している場合、ホーム
ディレクトリがマウントされておらず、このファイルをimportした時点で
失敗する。実行して失敗してから対処するのではなく、**先に**次を確認する。

    from pathlib import Path
    (Path.home() / "Documents" / "${LONGSTEP_DIRECTORY_NAME}").is_dir()

Falseだった場合は、次の順に対応すること。

1. ~/Documents/${LONGSTEP_DIRECTORY_NAME} へのアクセス許可（マウント）を
   ユーザーへ要求する。許可されればそのまま続行できる。
2. 仕組み上マウントできない場合は、実行したい処理を単体で動く
   pythonコマンドとしてユーザーへ提示し、手元で実行して結果を貼って
   もらう。このファイルのあるフォルダで動く。例：

       python3 -c "import longstep; print(longstep.list_goals())"
       python3 -c "import longstep; longstep.update_goal('<目標ID>', status='completed')"

【目標名の目安】
計画マップでの視認性のため、目標名（name）は10〜20文字程度を目安に簡潔に指定してください。
詳細な説明や参照ファイルは description へ記載します。

公開関数: get_plan_summary, list_goals, get_goal, update_plan,
add_goal, add_subgoal, update_goal, delete_goal
"""
from pathlib import Path
import sys

_PLAN_ID = ${planIdLiteral}
_LONGSTEP_DIR = Path.home() / "Documents" / "${LONGSTEP_DIRECTORY_NAME}"
_TOOL_PATH = _LONGSTEP_DIR / "longstep.pyz"
_PLAN_PATH = _LONGSTEP_DIR / f"{_PLAN_ID}.json"

if not _TOOL_PATH.is_file() or not _PLAN_PATH.is_file():
    raise FileNotFoundError(
        f"Longstepのツールまたは計画JSONが見つかりません: {_LONGSTEP_DIR}。"
        "VMやサンドボックスで実行している場合は、このディレクトリがマウントされていない可能性がある。"
        "ユーザーへアクセス許可を依頼すること。"
    )

sys.path.insert(0, str(_TOOL_PATH))
from longstep_tool import add_goal as _add_goal
from longstep_tool import add_subgoal as _add_subgoal
from longstep_tool import delete_goal as _delete_goal
from longstep_tool import get_goal as _get_goal
from longstep_tool import get_plan_summary as _get_plan_summary
from longstep_tool import list_goals as _list_goals
from longstep_tool import update_goal as _update_goal
from longstep_tool import update_plan as _update_plan


def get_plan_summary():
    """計画ID・計画名・最終目標・revisionを辞書で返す。"""
    return _get_plan_summary(_PLAN_PATH)


def list_goals(*, status=None, goal_level=None, fields=None):
    """list_goals(status=, goal_level=, fields=) -> 目標一覧を返す。
    デフォルトは [{'id': ..., 'name': ..., 'status': ...}, ...] を返す。
    fields='all' で全項目、fields=['name', 'target_date'] 等で指定項目のみ取得可能。
    """
    return _list_goals(_PLAN_PATH, status=status, goal_level=goal_level, fields=fields)


def get_goal(goal_id, *, fields="all"):
    """get_goal(goal_id, fields='all') -> 指定目標（IDまたは名前）の全項目と関連目標を持つ辞書。"""
    return _get_goal(_PLAN_PATH, goal_id, fields=fields)


def update_plan(**changes):
    """update_plan(name=, statement=, deadline=, success_criteria=) -> 更新結果。指定項目だけ更新する。"""
    return _update_plan(_PLAN_PATH, **changes)


def add_goal(name, **fields):
    """add_goal(name, target_date=, description=, next_action=, goal_level=, depends_on=, recurrence_enabled=, recurrence_cadence=, completed_count=) -> 更新結果。目標名(name)は10〜20文字程度を目安にし、詳細はdescriptionへ記載する。"""
    return _add_goal(_PLAN_PATH, name, **fields)


def add_subgoal(parent, name, **fields):
    """add_subgoal(parent, name, target_date=, description=, next_action=, goal_level=, recurrence_enabled=, recurrence_cadence=, completed_count=) -> 更新結果。親目標（IDまたは名前）の前提となるサブ目標（小目標）を追加する。"""
    return _add_subgoal(_PLAN_PATH, parent, name, **fields)


def update_goal(goal_id, **changes):
    """update_goal(goal_id, name=, status=, target_date=, description=, next_action=, goal_level=, depends_on=, recurrence_enabled=, recurrence_cadence=, completed_count=) -> 更新結果。目標名(name)を変更する場合は10〜20文字程度を目安にする。goal_idにはIDまたは目標名を指定可能。"""
    return _update_goal(_PLAN_PATH, goal_id, **changes)


def delete_goal(goal_id):
    """delete_goal(goal_id) -> revisionと削除対象を持つ更新結果。goal_idにはIDまたは目標名を指定可能。"""
    return _delete_goal(_PLAN_PATH, goal_id)
`
}
